### ISSUE TITLE
Inputs & missing pages

### ISSUE THREAD

**Issue by joergmis** [Startup-Nights/website#104]
- [x] add pitching competition to landing page #73 
- [x] update the programme page with formats, speakers, ...
- [x] update the impressions page with movies and better pictures
- [x] startup city winterthur page
- [x] update the partner page and process #102 
- [x] add an faq page #100 with location, transport, hotels, ... --> integrated the page and in the menu, now the only thing missing is the content
- [x] cookie banner #53 --> checkout https://www.ccm19.de

**Comment by joergmis** [comment]
Other small things that we have to tackle at some point:

- [ ] page with all the startups that have a booth -> all that are marked as "approved" in the booth signup sheet
- [ ] design + text of [pitching signup](http://localhost:3000/pitching)
- [ ] design + text + content of [program page](http://localhost:3000/program)
