### ISSUE TITLE
Open topics for the launch in May

### ISSUE THREAD

**Issue by joergmis** [Startup-Nights/website#45]
A list to keep track of the most important tasks for the launch.

- [x] #25 
- [x] update remaining positions from the hiring page
- [x] update the team members
- [x] #21 
- [x] SEO related - OG data to make sure we have a nice overview when people post a link on LinkedIn
- [x] SEO related - robots.txt
- [x] #10 
- [x] #16 - check if the stuff still works
- [x] #24 - check if the form still works
- [x] mobile / responsive design
- [x] #11 - and related: impressions page
- [x] mobile menu has no ticket button yet
- [x] ticket button has to open pre-register form until the ticketing launch - then it can link to to the `/tickets` page
- [x] backup the old website (+ download the backup) and create some footage of it (to be able to refer to it later on)
- [x] cross-check the facts and figures mentioned on the website - are they real and are they what is communicated?
- [x] facts and figures: matching icons

Set up the forwarding:

- [x] partner documentation had some links if I remember correctly
- [x] hiring.startup-nights.ch -> startup-nights.ch/hiring
- [x] ecw hiring page links to hiring.startup-nights.ch --> ping them in slack to adjust the link

In the worst case: add a note on the hiring page that the jobs have moved.
